name: hauth
version: 0.1.0.0
description: Please see the README on GitHub at <https://github.com/githubuser/hauth#readme>
author: Denis Angelov
maintainer: 
copyright: 2020 Denis Angelov
license: BSD3
github: githubuser/hauth
extra-source-files:
- README.md
- ChangeLog.md
dependencies:
- base >=4.7 && <5
- classy-prelude
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
library:
  source-dirs: src
  exposed-modules:
  - Lib
executables:
  hauth-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth


tests:
  hauth-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hauth
